version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_local
    environment:
      POSTGRES_DB: devmate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    restart: always

  devmate-application:
    container_name: devmate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
